name: deploy opac-page

on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "calloc134/opac-automation"

      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          # cache-dependency-path: "./pnpm-lock.yaml"

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          pnpm install

      - name: Run program
        run: |
          bun start
        env:
          USER_ID: ${{ secrets.USER_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          OPENAM_URL: ${{ secrets.OPENAM_URL }}
          ILISWAVE_URL: ${{ secrets.ILISWAVE_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opac-output-json
          path: opac-automation/output.json

  astro:
    runs-on: ubuntu-latest

    needs: bot

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "calloc134/opac-astro"

      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: opac-output-json

      - name: Run program
        run: |
          pnpm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opac-astro
          path: ./dist
