name: deploy opac-page

on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "calloc134/opac-automation"
          path: "opac-automation"

      - name: Install dependencies
        working-directory: opac-automation
        run: |
          pnpm install

      - name: Run program
        working-directory: opac-automation
        run: |
          bun start
